-- Run this script in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin'
);

CREATE TABLE IF NOT EXISTS programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  end_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT REFERENCES programs(id) ON DELETE CASCADE,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS trainees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT REFERENCES programs(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT
);

CREATE TABLE IF NOT EXISTS grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainee_id BIGINT REFERENCES trainees(id) ON DELETE CASCADE,
  topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
  score INTEGER CHECK(score >= 0 AND score <= 100),
  status TEXT, -- 'pass' or 'fail'
  UNIQUE(trainee_id, topic_id)
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  username TEXT,
  action TEXT,
  details TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Insert default admin user
INSERT INTO users (username, password, role) 
VALUES ('admin', 'admin123', 'admin')
ON CONFLICT (username) DO NOTHING;
